require "test_helper"
require "json"
require "csv"

# Guards the committed OpenAlex snapshot. It is generated by a network script, so
# the failure mode is a partial or malformed fetch getting committed — which would
# look like a successful build with a filter that quietly matches fewer journals.
class TestOpenAlexSnapshot < Minitest::Test
  ROOT = File.expand_path("..", __dir__)

  def snapshot
    @snapshot ||= JSON.parse(File.read(File.join(ROOT, "data", "openalex-subfields.json")))
  end

  def by_eissn
    snapshot["by_eissn"]
  end

  def test_matches_the_vast_majority_of_csv_eissns
    wanted = CSV.read(File.join(ROOT, "data", "northwestern-agreements.csv"),
                      headers: true, encoding: "UTF-8")
                .map { |r| r["eISSN"].to_s.strip }
                .select { |v| v.match?(/\A\d{4}-\d{3}[\dX]\z/) }
                .uniq
    matched = wanted.count { |issn| by_eissn.key?(issn) }
    assert_operator matched.to_f / wanted.length, :>=, 0.95,
                    "only #{matched} of #{wanted.length} eISSNs have subject data; " \
                    "re-run `ruby bin/fetch_openalex`"
  end

  def test_every_key_is_a_well_formed_eissn
    by_eissn.each_key do |issn|
      assert_match(/\A\d{4}-\d{3}[\dX]\z/, issn)
    end
  end

  def test_every_entry_is_subfield_id_and_positive_count_pairs
    by_eissn.first(200).each do |issn, subfields|
      refute_empty subfields, "#{issn} has an empty subfield list"
      subfields.each do |pair|
        assert_equal 2, pair.length, "#{issn} has a malformed pair #{pair.inspect}"
        assert_match(/\A\d+\z/, pair[0], "#{issn} has a non-numeric subfield id")
        assert_operator pair[1], :>, 0, "#{issn} has a non-positive article count"
      end
    end
  end

  def test_subfields_are_sorted_largest_first
    # The safety net in lib/disciplines.rb takes "the three largest", and while it
    # re-sorts defensively, a snapshot that is not already sorted means the fetch
    # script changed behaviour.
    by_eissn.first(200).each do |issn, subfields|
      counts = subfields.map { |(_, count)| count }
      assert_equal counts.sort.reverse, counts, "#{issn} is not sorted by count"
    end
  end

  def test_a_known_journal_resolves_to_its_expected_subject
    # JACS, whose largest subfield is Organic Chemistry (1605) by a wide margin.
    jacs = by_eissn["1520-5126"]
    refute_nil jacs, "JACS (1520-5126) missing from the snapshot"
    assert_equal "1605", jacs.first[0]
  end
end
